services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.twig_extension:
        class: FrontBundle\Twig\AppExtension
        arguments: ["@service_container"]
        public: true
        tags:
            - { name: twig.extension }