services:
    admin.user:
        class: AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - ApiBundle\Entity\Muser
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]