muser_index:
    path:     /
    defaults: { _controller: "AdminBundle:Muser:index" }
    methods:  GET
    
muser_list_ajax:
    path:     /user-list-ajax
    defaults: { _controller: "AdminBundle:Muser:userListAjax" }
    methods:  GET    

muser_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Muser:show" }
    methods:  GET

muser_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Muser:new" }
    methods:  [GET, POST]

muser_edit:
    path:     /{internalToken}/edit
    defaults: { _controller: "AdminBundle:Muser:edit" }
    methods:  [GET, POST]

muser_delete:
    path:     /{internalToken}/delete
    defaults: { _controller: "AdminBundle:Muser:delete" }
    methods:  [GET, POST]
    
muser_enable:
    path:     /{internalToken}/enable
    defaults: { _controller: "AdminBundle:Muser:enable" }
    methods:  [GET, POST]    
    
mphoto_manage:
    path:     /{internalToken}/photo-manage
    defaults: { _controller: "AdminBundle:Muser:managePhoto" }
    methods:  [GET, POST] 
    
mpassword_new:
    path:     /{internalToken}/new/password
    defaults: { _controller: "AdminBundle:Muser:newPassword" }
    methods:  [GET, POST]     
    
