imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ApiBundle/Resources/config/config.yml" }
    - { resource: "@ApiBundle/Resources/config/services.yml" }
    - { resource: "@MiddleBundle/Resources/config/services.yml" }
    - { resource: "@FrontBundle/Resources/config/services.yml" }
    - { resource: "@MobileBundle/Resources/config/services.yml" }
    - { resource: "@TestBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    api_application_key: ibJg1A6N8yOIVK158aFYHksSTaW0WCPHHn1rNbP38hYza6T9xSjv6eCDT570R6gslFP02P5E0uPmVd0fmp3Ksp5wisUUU9dztngtqBBcivuvOHa7qyvXrzdcuxWHxCLl
    api_version : 0
    locale: zh_CN
    min_top_time: 1800
    service_mail: service@xxx.com
    cc_mail: cc@xxx.com
    upload_directory: "uploads/"
    profile_photo_directory: "profile/"
    user_photo_directory: "user/"
    post_photo_directory: "post/"
    original_directory: "original/"
    medium_directory: "medium/"
    small_directory: "small/"
    size_limit_photo: 2097152
    medium_photo_max_width: 500
    small_photo_max_width: 150
    icon_photo_max_width: 50
    photo_default_mime_type: "image/png"
    photo_default_type: ".png"
    cache.dsn.default: "redis://localhost"
    cache.dsn.user: "redis://localhost/1"
    cache.dsn.post: "redis://localhost/2"
    cache.dsn.userPhotos: "redis://localhost/3"
    cache.dsn.postPhotos: "redis://localhost/4"
    cache.dsn.profilePhotos: "redis://localhost/5"
    cache.dsn.searchUsers: "redis://localhost/6"
    cache.userWithUsername: "userWithUsername"
    cache.userPhotos: "userPhotos"
    cache.profilePhotos: "profilePhotos"
    cache.post: "post"
    cache.postPhotos: "postPhotos"
    cache.searchUsers: "searchUsers"
    search.host: "localhost"
    search.port: 9200
    search.user.numberResults: 15
    search.post.numberResults: 15
    fos_elastica.index_manager: "fos_elastica.index_manager"


framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: snc_redis.session.handler
        #handler_id:  session.handler.native_file
        #save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: 
        version: 'v1.0'
        version_format: '%%s?version=%%s'
    php_errors:
        log: true


assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    filters:
        cssrewrite: ~
        
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        #default_connection: default
        #connections:
        #    default:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
                # if using pdo_sqlite as your database driver:
                #   1. add the path in parameters.yml
                #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
                #   2. Uncomment database_path in parameters.yml.dist
                #   3. Uncomment next line:
                #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    #spool:     { type: memory }          
            
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []
        origin_regex: false
 
            
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %cache.dsn.default%
            logging: %kernel.debug%
        user:
            type: predis
            alias: user
            dsn: %cache.dsn.user%
            logging: true
        post:
            type: predis
            alias: post
            dsn: %cache.dsn.post%
            logging: true
        userPhotos:
            type: predis
            alias: userPhotos
            dsn: %cache.dsn.userPhotos%
            logging: true
        postPhotos:
            type: predis
            alias: postPhotos
            dsn: %cache.dsn.postPhotos%
            logging: true
        profilePhotos:
            type: predis
            alias: profilePhotos
            dsn: %cache.dsn.profilePhotos%
            logging: true    
        searchUsers:
            type: predis
            alias: searchUsers
            dsn: %cache.dsn.searchUsers%
            logging: true        
    session:
            client: default
            prefix: session
            ttl: 36000


fos_elastica:
    clients:
        default: { host: %search.host%, port: %search.port% }
    indexes:
        app:
            client: default
            use_alias: true
            index_name: app_massage_%kernel.environment%
            types:
                post:
                    properties:
                    mappings:
                                id:
                                    type: keyword
                                    index: not_analyzed
                                userId: 
                                    type: keyword
                                    index: not_analyzed
                                internalId:
                                    type: keyword
                                    index: not_analyzed
                                title: 
                                    type: text
                                    boost: 10
                                description:  
                                    type: text
                                    boost: 5
                                displayedHome:
                                    type: keyword
                                    index: not_analyzed
                                viewNumber:
                                    type: keyword
                                    index: not_analyzed
                                isFromOtherWeb:
                                    type: keyword
                                    index: not_analyzed
                                otherWeb:
                                    type: keyword
                                    index: not_analyzed
                                isDeleted:                                    
                                    type: keyword
                                    index: not_analyzed
                                deletedByUserId:
                                    type: keyword
                                    index: not_analyzed
                                slug:                                    
                                    type: keyword
                                    index: not_analyzed
                                topTime:
                                    type: date
                                    index: not_analyzed 
                                created:
                                    type: date
                                    index: not_analyzed
                                updated:
                                    type: date
                                    index: not_analyzed    
                    persistence:
                                #identifier: internalId
                                driver: orm
                                model: ApiBundle\Entity\Mpost
                                provider: 
                                    debug_logging: false
                                finder: ~   
                                listener: 
                                    insert: false
                                    update: false
                                    delete: false
                                    logger: false
                                elastica_to_model_transformer:
                                    ignore_missing: true                
                                                                                                            
                user:               
                    properties:
                                birthday:
                                    type: date
                                    format: "yyyy-MM-dd"
                                token:
                                    property_path: false
                                internalToken:
                                    property_path: false
                                externalToken:    
                                    property_path: false
                    mappings:
                                id:
                                    type: keyword
                                    index: not_analyzed
                                username: 
                                    type: keyword
                                    boost: 5
                                email: 
                                    type: keyword
                                    boost: 1
                                telephone: 
                                    type: keyword
                                    boost: 1
                                nickname:
                                    type: text
                                    boost: 5
                                wechat:
                                    type: text
                                    boost: 5
                                facebook:
                                    type: text
                                    index: not_analyzed
                                instagram:
                                    type: text
                                    index: not_analyzed
                                website:
                                    type: text
                                    index: not_analyzed
                                timezone:
                                    type: keyword
                                    index: not_analyzed
                                country:
                                    type: text
                                    boost: 1
                                city:
                                    type: text
                                    boost: 1
                                postNumber:
                                    type: keyword
                                    index: not_analyzed
                                countryId:
                                    type: keyword
                                    index: not_analyzed
                                locationId:
                                    type: keyword
                                    index: not_analyzed
                                skinColor:
                                    type: keyword
                                    index: not_analyzed
                                birthday:
                                    type: date
                                    #format: "yyyy-MM-dd"
                                    index: not_analyzed
                                shopAddress:
                                    type: text
                                    boost: 10
                                shopName: 
                                    type: text
                                    boost: 10
                                description:
                                    type: text
                                    boost: 5
                                translatedDescription:
                                    type: text
                                    boost: 5
                                isActive:
                                    type: keyword
                                    index: not_analyzed
                                isDeleted:
                                    type: keyword
                                    index: not_analyzed
                                isPremium:
                                    type: keyword
                                    index: not_analyzed
                                isSingle:
                                    type: keyword
                                    index: not_analyzed
                                isShop:
                                    type: keyword
                                    index: not_analyzed
                                isZh:
                                    type: keyword
                                    index: not_analyzed
                                isEn:
                                    type: keyword
                                    index: not_analyzed
                                isFr:
                                    type: keyword
                                    index: not_analyzed
                                isTest:
                                    type: keyword
                                    index: not_analyzed
                                isFromOtherWeb:
                                    type: keyword
                                    index: not_analyzed
                                otherWeb:
                                    type: keyword
                                    index: not_analyzed
                                otherWebReference:
                                    type: keyword
                                    index: not_analyzed
                                draftId:
                                    type: keyword
                                    index: not_analyzed
                                slug:
                                    type: keyword
                                    index: not_analyzed
                                internalId:
                                    type: keyword
                                    index: not_analyzed
                                topTime:
                                    type: date
                                    #format: date_hour_minute_second
                                    index: not_analyzed
                                lastSynchronizedFromOtherWebTime:
                                    type: date
                                    #format: date_hour_minute_second
                                    index: not_analyzed
                                paymentExpiredTime:
                                    type: date
                                    #format: date_hour_minute_second
                                    index: not_analyzed
                                created:
                                    type: date
                                    #format: date_hour_minute_second
                                    index: not_analyzed
                                updated:
                                    type: date
                                    #format: date_hour_minute_second
                                    index: not_analyzed
                    persistence:
                                #identifier: internalId
                                driver: orm
                                model: ApiBundle\Entity\Muser
                                provider: 
                                    debug_logging: false
                                finder: ~   
                                listener: 
                                    insert: false
                                    update: false
                                    delete: false
                                    logger: false
                                elastica_to_model_transformer:
                                    #hydrate: false
                                    ignore_missing: true