test:
    resource: "@TestBundle/Controller/"
    type:     annotation
    prefix:   /test

mobile:
    resource: "@MobileBundle/Resources/config/routing.yml"
    prefix:   /mobile

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /front

middle:
    resource: "@MiddleBundle/Resources/config/routing.yml"
    prefix:   /middle

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /3721

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /3721      