mobile:
    resource: "@MobileBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

middle:
    resource: "@MiddleBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
