# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        ApiBundle\Entity\Muser:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    
    firewalls:
        secured_area:
            pattern: ^/middle/private
            stateless: false
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider
            
    providers:
        api_key_user_provider:
            id: api_key_user_provider

        #in_memory:
            #memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html



    access_control:
        - { path: ^/middle/private, roles: ROLE_API }