# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    api_key_user_provider:
        class: ApiBundle\Security\ApiKeyUserProvider
        arguments: ["@service_container"]
        
    apikey_authenticator:
        class:  ApiBundle\Security\ApiKeyAuthenticator
        public: false    
        arguments: ["@service_container"]