ApiBundle\Entity\Mpassword:
    type: entity
    table: mpassword
    indexes:
        user_id:
            columns:
                - user_id
        password:
            columns:
                - password
        salt:
            columns:
                - salt
        encryption_method:
            columns:
                - encryption_method
        indication:
            columns:
                - indication
    uniqueConstraints:
        internal_id:
            columns:
                - internal_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        encryptionMethod:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: encryption_method
        salt:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        indication:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        internalId:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: internal_id
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false
    manyToOne:
        user:
            targetEntity: Muser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
