ApiBundle\Entity\Mpost:
    type: entity
    table: mpost
    repositoryClass: ApiBundle\Repository\MassagePostRepository
    indexes:
        user_id:
            columns:
                - user_id
        title:
            columns:
                - title
    uniqueConstraints:
        internal_id:
            columns:
                - internal_id
        slug:
            columns:
                - slug
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: string
            nullable: false
            length: 11
            options:
                fixed: false
            column: user_id
        internalId:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: internal_id
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: blob
            nullable: false
            length: 65535
            options:
                fixed: false
        displayedHome:
            type: boolean
            nullable: true
            column: displayed_home
        viewNumber:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: view_number
        isFromOtherWeb:
            type: boolean
            nullable: true
            column: is_from_other_web
        otherWeb:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: other_web
        isDeleted:
            type: boolean
            nullable: true
            column: is_deleted
            options:
                default: '0'
        deletedByUserId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: deleted_by_user_id    
        isSynchronizedByCache:
            type: boolean
            nullable: true
            column: is_synchronized_by_cache
        isSynchronizedBySearch:
            type: boolean
            nullable: true
            column: is_synchronized_by_search
        slug:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        topTime:
            type: datetime
            nullable: true
            column: top_time
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false
    manyToOne:
        user:
            targetEntity: Muser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
