api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
    
public_api_login:
    path: /public/user/login
    defaults: { _controller: ApiBundle:PublicUser:login, _format:json}
    methods:  [POST]
    
public_api_create_user:
    path: /public/user/create
    defaults: { _controller: ApiBundle:PublicUser:createUser, _format:json}
    methods:  [POST]    
    
public_api_user_forget_password:
    path: /public/user/forget/password
    defaults: { _controller: ApiBundle:PublicUser:forgetPassword, _format:json}
    methods:  [POST]  
    
public_api_user_reset_password:
    path: /private/user/reset/password
    defaults: { _controller: ApiBundle:PrivateUser:resetPassword, _format:json}
    methods:  [POST]

public_api_user_reset_email:
    path: /private/user/reset/email
    defaults: { _controller: ApiBundle:PrivateUser:resetEmail, _format:json}
    methods:  [POST]
    
public_api_user_reset_telephone:
    path: /private/user/reset/telephone
    defaults: { _controller: ApiBundle:PrivateUser:resetTelephone, _format:json}
    methods:  [POST]    
    
public_api_user_update_info:
    path: /private/user/update/info
    defaults: { _controller: ApiBundle:PrivateUser:updateUserInfo, _format:json}
    methods:  [POST]     