api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
    
public_api_login:
    path: /public/user/login
    defaults: { _controller: ApiBundle:PublicUser:login, _format:json}
    methods:  [POST]
    
public_api_create_user:
    path: /public/user/create
    defaults: { _controller: ApiBundle:PublicUser:createUser, _format:json}
    methods:  [POST]    
    
public_api_user_forget_password:
    path: /public/user/forget/password
    defaults: { _controller: ApiBundle:PublicUser:forgetPassword, _format:json}
    methods:  [POST]  
    
private_api_user_reset_password:
    path: /private/user/reset/password
    defaults: { _controller: ApiBundle:PrivateUser:resetPassword, _format:json}
    methods:  [POST]

private_api_user_reset_email:
    path: /private/user/reset/email
    defaults: { _controller: ApiBundle:PrivateUser:resetEmail, _format:json}
    methods:  [POST]
    
private_api_user_reset_telephone:
    path: /private/user/reset/telephone
    defaults: { _controller: ApiBundle:PrivateUser:resetTelephone, _format:json}
    methods:  [POST]    
    
private_api_user_update_info:
    path: /private/user/update/info
    defaults: { _controller: ApiBundle:PrivateUser:updateUserInfo, _format:json}
    methods:  [POST]  
    
private_api_shop_update_info:
    path: /private/shop/update/info
    defaults: { _controller: ApiBundle:PrivateUser:updateShopInfo, _format:json}
    methods:  [POST]      
    
private_api_new_user_send_mail:
    path: /private/user/new/send/mail
    defaults: { _controller: ApiBundle:PrivateUser:sendNewUserMail, _format:json}
    methods:  [POST]   
    
private_api_password_changed_send_mail:
    path: /private/user/password/changed/send/mail
    defaults: { _controller: ApiBundle:PrivateUser:sendPasswordChangedMail, _format:json}
    methods:  [POST]   
    
public_api_password_forget_send_mail:
    path: /private/user/password/forget/send/mail
    defaults: { _controller: ApiBundle:PrivateUser:sendPasswordForgetMail, _format:json}
    methods:  [POST]     
    
private_api_uploader:
    path: /private/user/upload/photo
    defaults: { _controller: ApiBundle:PrivateUser:upload, _format:json}
    methods:  [POST]

public_api_user_page:
    path: /public/user/single/page
    defaults: { _controller: ApiBundle:PublicUser:getSingleUserPage, _format:json}
    methods:  [POST]
    
public_api_shop_page:
    path: /public/shop/single/page
    defaults: { _controller: ApiBundle:PublicUser:getSingleShopPage, _format:json}
    methods:  [POST]    

public_api__remove_user_page_cache:
    path: /public/user/single/page/remove/cache
    defaults: { _controller: ApiBundle:PublicUser:removeSingleUserPageCache, _format:json}
    methods:  [POST]
    
public_api_user_photos:
    path: /public/user/photos
    defaults: { _controller: ApiBundle:PublicUser:getSingleUserPhotos, _format:json}
    methods:  [POST] 
    
public_api_profile_photo:
    path: /public/profile/photo
    defaults: { _controller: ApiBundle:PublicUser:getProfilePhoto, _format:json}
    methods:  [POST]     
    
public_api_user_search:
    path: /public/user/search
    defaults: { _controller: ApiBundle:PublicUser:searchUser, _format:json}
    methods:  [POST]     