api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
    
public_api_generate_random_string:
    path:     /public/rs/s4IPvSlIpZaAzZjk32zgguXsmBxTsGWL
    defaults: { _controller: ApiBundle:Default:generateRandomString , _format:json} 
    
public_api_client_ip:
    path:     /public/ci/mJemHziBpaw8GllwVIk98U96urNapR2Z.{_format}
    defaults: { _controller: ApiBundle:Default:clientIp , _format:json}    
  
public_api_searchengine_state:
    path:     /public/ss/IoUHL2m6wNCc8N9sIyams5iYTuTKItqd.{_format}
    defaults: { _controller: ApiBundle:Default:searchEngineState , _format:json}         
    
public_api_login:
    path: /public/ul/QZgETAYn3Kw7SkOAHHhEOf1YsjDiawDA.{_format}
    defaults: { _controller: ApiBundle:PublicUser:login, _format:json}
    methods:  [POST]
    
public_api_create_user:
    path: /public/uc/uXQ3PdRDIpwbTECgg4Ae9AxCaFIViqL1.{_format}
    defaults: { _controller: ApiBundle:PublicUser:createUser, _format:json}
    methods:  [POST]    
    
public_api_user_forget_password:
    path: /public/user/forget/password
    defaults: { _controller: ApiBundle:PublicUser:forgetPassword, _format:json}
    methods:  [POST]  
    
private_api_user_reset_password:
    path: /private/urp/ixBuSee1zKP8B2zjarerV0CBHT9nfPZs.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:resetPassword, _format:json}
    methods:  [POST]

private_api_user_reset_email:
    path: /private/ure/qQrSbOckK85PNxdVr5r5J74QcL6WXYso.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:resetEmail, _format:json}
    methods:  [POST]
    
private_api_user_reset_telephone:
    path: /private/urt/94Qc2PStROlisSdlOnWJBRKEcJ0DiqPf.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:resetTelephone, _format:json}
    methods:  [POST]    
    
private_api_user_update_info:
    path: /private/uui/RUWj1jizt0WjvMJUqFJwks5cGjuc7MEY.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:updateUserInfo, _format:json}
    methods:  [POST]  
    
private_api_shop_update_info:
    path: /private/sui/teI0mLYe4xvpZqxLPYTjxKHhBLHS4abc.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:updateShopInfo, _format:json}
    methods:  [POST]      
    
private_api_new_user_send_mail:
    path: /private/unsm/sendjdkdshedjcksjdjejdjqiehdusjzs.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:sendNewUserMail, _format:json}
    methods:  [POST]   
    
private_api_password_changed_send_mail:
    path: /private/upcsm/teI0mLYe4xvpZqxLPYTjxKHhdghjnbcz.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:sendPasswordChangedMail, _format:json}
    methods:  [POST]   
    
public_api_password_forget_send_mail:
    path: /public/upfsm/nuyOR8Ps3xT4oWggrzDk4KzrO2Ydc5LD.{_format}
    defaults: { _controller: ApiBundle:PublicUser:sendPasswordForgetMail, _format:json}
    methods:  [POST]     
    
private_api_uploader:
    path: /private/user/upload/photo
    defaults: { _controller: ApiBundle:PrivateUser:upload, _format:json}
    methods:  [POST]

public_api_user_page:
    path: /public/usp/FQy21dV1zx0wpGgSzMf5nHHIbnXIcX4o.{_format}
    defaults: { _controller: ApiBundle:PublicUser:getSingleUserPage, _format:json}
    methods:  [POST]
    
public_api_shop_page:
    path: /public/ssp/gOzX8eZ54yZEbOCz3Zevjrq47XUrb7b3.{_format}
    defaults: { _controller: ApiBundle:PublicUser:getSingleShopPage, _format:json}
    methods:  [POST]    

public_api__remove_user_page_cache:
    path: /public/usprc/QcUrTSqRbB9kx0iQX2149IIAFbHmdgr1.{_format}
    defaults: { _controller: ApiBundle:PublicUser:removeSingleUserPageCache, _format:json}
    methods:  [POST]
    
public_api_user_photos:
    path: /public/up/Db2FUBxAmlMeSR257ySQTw77kiyRWCdZ.{_format}
    defaults: { _controller: ApiBundle:PublicUser:getSingleUserPhotos, _format:json}
    methods:  [POST] 
    
public_api_profile_photo:
    path: /public/pp/hgeusPjrI9H6AS3m4knn4m4fpjsCJ8yz.{_format}
    defaults: { _controller: ApiBundle:PublicUser:getProfilePhoto, _format:json}
    methods:  [POST]     
    
public_api_user_search:
    path: /public/us/CkHbQ50W23tTSwK9YiYU7yyJiSFa7uXq.{_format}
    defaults: { _controller: ApiBundle:PublicUser:searchUser, _format:json}
    methods:  [POST] 
    
public_api_remove_user_search_cache:
    path: /public/usrc/hm7RuoNdy67z479uMrpF80xxJluf5HUX.{_format}
    defaults: { _controller: ApiBundle:PublicUser:removeSearchUserCache, _format:json}
    methods:  [POST]     
    
public_api_post_search:
    path: /public/ps/peVVra1KVSbTNeZwid4UyT22gSApB8VM.{_format}
    defaults: { _controller: ApiBundle:PublicPost:searchPost, _format:json}
    methods:  [POST]     
    
private_api_topuser:
    path: /private/ut/kGn1KnNEVQGCPdbYrT2lzOFlNWhpdaTN.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:topUser, _format:json}
    methods:  [POST]    
    
private_api_photo_delete:
    path: /private/phd/hxJ182uoG9etkVyp8O3Rapo018oZKD2p.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:deletePhoto, _format:json}
    methods:  [POST]        
    
public_api_post_page:
    path: /public/psp/ApbSnnOoXxrvI8MiHYeOlK9aaG5LkaMV.{_format}
    defaults: { _controller: ApiBundle:PublicPost:getSinglePostPage, _format:json}
    methods:  [POST]    
    
public_api_create_post:
    path: /private/pc/vivUeFaGjacPOnE8WMQcOWSm0vhg142P.{_format}
    defaults: { _controller: ApiBundle:PrivatePost:createPost, _format:json}
    methods:  [POST]      
    
private_api_post_delete:
    path: /private/pd/JIM2Nr2gRo4XYHfAxFTykdtwvqbEihIz.{_format}
    defaults: { _controller: ApiBundle:PrivatePost:deletePost, _format:json}
    methods:  [POST]   

private_api_post_update:
    path: /private/pu/blSqcFfCDXr198oX2FPrKgqJfuWCUt32.{_format}
    defaults: { _controller: ApiBundle:PrivatePost:updatePost, _format:json}
    methods:  [POST]     
    