api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
    
public_api_generate_random_string:
    path:     /public/random/string
    defaults: { _controller: ApiBundle:Default:generateRandomString } 
    
public_api_client_ip:
    path:     /public/client/ip
    defaults: { _controller: ApiBundle:Default:clientIp }    
  
public_api_searchengine_state:
    path:     /public/searchengine/state
    defaults: { _controller: ApiBundle:Default:searchEngineState }      
    
public_api_login:
    path: /public/user/login
    defaults: { _controller: ApiBundle:PublicUser:login, _format:json}
    methods:  [POST]
    
public_api_create_user:
    path: /public/user/create
    defaults: { _controller: ApiBundle:PublicUser:createUser, _format:json}
    methods:  [POST]    
    
public_api_user_forget_password:
    path: /public/user/forget/password
    defaults: { _controller: ApiBundle:PublicUser:forgetPassword, _format:json}
    methods:  [POST]  
    
private_api_user_reset_password:
    path: /private/user/reset/password
    defaults: { _controller: ApiBundle:PrivateUser:resetPassword, _format:json}
    methods:  [POST]

private_api_user_reset_email:
    path: /private/user/reset/email
    defaults: { _controller: ApiBundle:PrivateUser:resetEmail, _format:json}
    methods:  [POST]
    
private_api_user_reset_telephone:
    path: /private/user/reset/telephone
    defaults: { _controller: ApiBundle:PrivateUser:resetTelephone, _format:json}
    methods:  [POST]    
    
private_api_user_update_info:
    path: /private/uui/RUWj1jizt0WjvMJUqFJwks5cGjuc7MEY.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:updateUserInfo, _format:json}
    methods:  [POST]  
    
private_api_shop_update_info:
    path: /private/sui/teI0mLYe4xvpZqxLPYTjxKHhBLHS4abc.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:updateShopInfo, _format:json}
    methods:  [POST]      
    
private_api_new_user_send_mail:
    path: /private/unsm/sendjdkdshedjcksjdjejdjqiehdusjzs.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:sendNewUserMail, _format:json}
    methods:  [POST]   
    
private_api_password_changed_send_mail:
    path: /private/upcsm/teI0mLYe4xvpZqxLPYTjxKHhdghjnbcz.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:sendPasswordChangedMail, _format:json}
    methods:  [POST]   
    
public_api_password_forget_send_mail:
    path: /private/upfsm/nuyOR8Ps3xT4oWggrzDk4KzrO2Ydc5LD.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:sendPasswordForgetMail, _format:json}
    methods:  [POST]     
    
private_api_uploader:
    path: /private/user/upload/photo
    defaults: { _controller: ApiBundle:PrivateUser:upload, _format:json}
    methods:  [POST]

public_api_user_page:
    path: /public/user/single/page
    defaults: { _controller: ApiBundle:PublicUser:getSingleUserPage, _format:json}
    methods:  [POST]
    
public_api_shop_page:
    path: /public/shop/single/page
    defaults: { _controller: ApiBundle:PublicUser:getSingleShopPage, _format:json}
    methods:  [POST]    

public_api__remove_user_page_cache:
    path: /public/user/single/page/remove/cache
    defaults: { _controller: ApiBundle:PublicUser:removeSingleUserPageCache, _format:json}
    methods:  [POST]
    
public_api_user_photos:
    path: /public/user/photos
    defaults: { _controller: ApiBundle:PublicUser:getSingleUserPhotos, _format:json}
    methods:  [POST] 
    
public_api_profile_photo:
    path: /public/profile/photo
    defaults: { _controller: ApiBundle:PublicUser:getProfilePhoto, _format:json}
    methods:  [POST]     
    
public_api_user_search:
    path: /public/user/search
    defaults: { _controller: ApiBundle:PublicUser:searchUser, _format:json}
    methods:  [POST] 
    
public_api_remove_user_search_cache:
    path: /public/user/search/remove/cache
    defaults: { _controller: ApiBundle:PublicUser:removeSearchUserCache, _format:json}
    methods:  [POST]     
    
public_api_post_search:
    path: /public/post/search
    defaults: { _controller: ApiBundle:PublicPost:searchPost, _format:json}
    methods:  [POST]     
    
private_api_topuser:
    path: /private/ut/kGn1KnNEVQGCPdbYrT2lzOFlNWhpdaTN.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:topUser, _format:json}
    methods:  [POST]    
    
private_api_photo_delete:
    path: /private/phd/hxJ182uoG9etkVyp8O3Rapo018oZKD2p.{_format}
    defaults: { _controller: ApiBundle:PrivateUser:deletePhoto, _format:json}
    methods:  [POST]        
    
public_api_post_page:
    path: /public/post/single/page
    defaults: { _controller: ApiBundle:PublicPost:getSinglePostPage, _format:json}
    methods:  [POST]    
    
public_api_create_post:
    path: /private/pc/vivUeFaGjacPOnE8WMQcOWSm0vhg142P.{_format}
    defaults: { _controller: ApiBundle:PrivatePost:createPost, _format:json}
    methods:  [POST]      
    
private_api_post_delete:
    path: /private/pd/JIM2Nr2gRo4XYHfAxFTykdtwvqbEihIz.{_format}
    defaults: { _controller: ApiBundle:PrivatePost:deletePost, _format:json}
    methods:  [POST]   

private_api_post_update:
    path: /private/pu/blSqcFfCDXr198oX2FPrKgqJfuWCUt32.{_format}
    defaults: { _controller: ApiBundle:PrivatePost:updatePost, _format:json}
    methods:  [POST]     
    