api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

public_api_login:
    path: /public/user/login
    defaults: { _controller: ApiBundle:PublicUser:login, _format:json}
    methods:  [POST]