api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

public_api_login:
    path: /public/login
    defaults: { _controller: ApiBundle:Public:login, _format:json}
    methods:  [POST]