services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    api_massage.UtileService:
            class: ApiBundle\Services\UtileService
            arguments: ["@translator.default"]
            
    api_massage.mailer:
        class:        ApiBundle\Services\Mailer
        arguments:    ["@mailer", "@templating"]        

    api_massage.UsersService:
            class: ApiBundle\Services\UsersService
            arguments: ["@doctrine","@session","@translator.default","@validator", "@service_container","@api_massage.UtileService", "@api_massage.mailer", "@api_massage.CacheService"]
#  "@service_container"

    api_massage.PhotoService:
            class: ApiBundle\Services\PhotoService
            arguments: ["@doctrine", "@api_massage.UsersService", "@api_massage.CacheService", "@api_massage.UtileService", "%size_limit_photo%", "%upload_directory%", "%profile_photo_directory%", "%user_photo_directory%", "%post_photo_directory%", "%original_directory%", "%medium_directory%", "%small_directory%", "%medium_photo_max_width%", "%small_photo_max_width%", "%icon_photo_max_width%", "%photo_default_mime_type%", "%photo_default_type%"]

    api_massage.CacheService:
            class: ApiBundle\Services\CacheService
            arguments: ["@service_container", "@api_massage.UtileService", "%cache.userWithUsername%", "%cache.userPhotos%"]
            
    api_massage.dataCreateListener:
            class: ApiBundle\EventListener\DataPersist
            #calls:
            #    - [setCacheService, ["@api_massage.CacheService"]]
            arguments: ["@api_massage.CacheService", "@api_massage.PhotoService"]
            tags:
                - { name: doctrine.event_listener, event: prePersist }

    api_massage.dataUpdateListener:
            class: ApiBundle\EventListener\DataPersist
            arguments: ["@api_massage.CacheService"]
            tags:
                - { name: doctrine.event_listener, event: preUpdate }