services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

api_massage.UtileService:
        class: ApiBundle\Services\UtileService
        arguments: ["@translator.default"]
        
api_massage.UsersService:
        class: ApiBundle\Services\UsersService
        arguments: ["@doctrine","@session","@translator.default","@service_container", "@api_cram.UtileService"]
        