
ApiBundle\Entity\Mpassword:  
    properties:
        password:
            - NotBlank:  
                message: 'user.password.not.blank' 
            - Length:
                min: 8
                minMessage: 'user.password.too.short'
            - Regex:
                pattern: '/^(?=.*[a-zA-Z])(?=.*[0-9]).+$/'
                match:   true
                message: 'user.password.complex.invalid'
                
ApiBundle\Entity\Muser:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [username]
            message: 'user.username.exist'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [telephone]
            message: 'user.telephone.exist'    
    properties:
        username:
            - NotBlank:  
                message: 'user.username.not.blank' 
            - Length:
                min: 3
                minMessage: 'user.username.too.short' 
        telephone:
            - NotBlank:  
                message: 'user.telephone.not.blank' 
            - Length:
                min: 8
                minMessage: 'user.telephone.too.short'     
                max: 20
                maxMessage: 'user.telephone.too.long' 
            - Regex:
                pattern: '/^[0-9]{8,20}$/'
                match:   true
                message: user.telephone.format.invalid    
        email:
            - Regex:
                pattern: '/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/'
                match:   true
                message: user.email.format.invalid 
        description:        
            - Length:  
                max: 255
                maxMessage: 'user.description.too.long' 
        translatedDescription:        
            - Length:  
                max: 255
                maxMessage: 'user.translatedDescription.too.long'        
ApiBundle\Entity\Mpost:
    properties:
        title:
            - NotBlank:  
                message: 'post.title.not.blank' 
            - Length:
                min: 3
                minMessage: 'post.title.too.short' 
        description:
            - NotBlank:  
                message: 'post.description.not.blank'   
            - Length:
                min: 10
                minMessage: 'post.description.too.short'                   